# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(731, 636)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../resources/icons/main/right.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(213, 20, 481, 561))
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 11, 181, 571))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.column_groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.column_groupBox.setMinimumSize(QtCore.QSize(0, 151))
        self.column_groupBox.setObjectName("column_groupBox")
        self.layoutWidget1 = QtWidgets.QWidget(self.column_groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(9, 30, 156, 110))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.h_label = QtWidgets.QLabel(self.layoutWidget1)
        self.h_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.h_label.setObjectName("h_label")
        self.gridLayout_2.addWidget(self.h_label, 0, 0, 1, 1)
        self.c1_spinBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.c1_spinBox.setMinimum(250)
        self.c1_spinBox.setMaximum(2000)
        self.c1_spinBox.setSingleStep(50)
        self.c1_spinBox.setProperty("value", 400)
        self.c1_spinBox.setObjectName("c1_spinBox")
        self.gridLayout_2.addWidget(self.c1_spinBox, 0, 1, 1, 1)
        self.c2_label = QtWidgets.QLabel(self.layoutWidget1)
        self.c2_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.c2_label.setObjectName("c2_label")
        self.gridLayout_2.addWidget(self.c2_label, 1, 0, 1, 1)
        self.c2_spinBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.c2_spinBox.setMinimum(250)
        self.c2_spinBox.setMaximum(2000)
        self.c2_spinBox.setSingleStep(50)
        self.c2_spinBox.setProperty("value", 400)
        self.c2_spinBox.setObjectName("c2_spinBox")
        self.gridLayout_2.addWidget(self.c2_spinBox, 1, 1, 1, 1)
        self.pos_label = QtWidgets.QLabel(self.layoutWidget1)
        self.pos_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pos_label.setObjectName("pos_label")
        self.gridLayout_2.addWidget(self.pos_label, 2, 0, 1, 1)
        self.pos_comboBox = QtWidgets.QComboBox(self.layoutWidget1)
        self.pos_comboBox.setMouseTracking(False)
        self.pos_comboBox.setObjectName("pos_comboBox")
        self.pos_comboBox.addItem("")
        self.pos_comboBox.addItem("")
        self.pos_comboBox.addItem("")
        self.gridLayout_2.addWidget(self.pos_comboBox, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.column_groupBox)
        self.foundation_groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.foundation_groupBox.setMinimumSize(QtCore.QSize(0, 231))
        self.foundation_groupBox.setObjectName("foundation_groupBox")
        self.widget = QtWidgets.QWidget(self.foundation_groupBox)
        self.widget.setGeometry(QtCore.QRect(16, 30, 147, 186))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.height_label = QtWidgets.QLabel(self.widget)
        self.height_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.height_label.setObjectName("height_label")
        self.gridLayout.addWidget(self.height_label, 0, 0, 1, 1)
        self.height_spinBox = QtWidgets.QSpinBox(self.widget)
        self.height_spinBox.setMinimum(100)
        self.height_spinBox.setMaximum(2000)
        self.height_spinBox.setSingleStep(50)
        self.height_spinBox.setProperty("value", 600)
        self.height_spinBox.setObjectName("height_spinBox")
        self.gridLayout.addWidget(self.height_spinBox, 0, 1, 1, 1)
        self.cover_label = QtWidgets.QLabel(self.widget)
        self.cover_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cover_label.setObjectName("cover_label")
        self.gridLayout.addWidget(self.cover_label, 1, 0, 1, 1)
        self.cover_spinBox = QtWidgets.QSpinBox(self.widget)
        self.cover_spinBox.setMinimum(20)
        self.cover_spinBox.setMaximum(100)
        self.cover_spinBox.setSingleStep(10)
        self.cover_spinBox.setProperty("value", 70)
        self.cover_spinBox.setObjectName("cover_spinBox")
        self.gridLayout.addWidget(self.cover_spinBox, 1, 1, 1, 1)
        self.fc_label = QtWidgets.QLabel(self.widget)
        self.fc_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fc_label.setObjectName("fc_label")
        self.gridLayout.addWidget(self.fc_label, 2, 0, 1, 1)
        self.fc_spinBox = QtWidgets.QSpinBox(self.widget)
        self.fc_spinBox.setMinimum(20)
        self.fc_spinBox.setMaximum(80)
        self.fc_spinBox.setSingleStep(5)
        self.fc_spinBox.setProperty("value", 20)
        self.fc_spinBox.setObjectName("fc_spinBox")
        self.gridLayout.addWidget(self.fc_spinBox, 2, 1, 1, 1)
        self.dl_label = QtWidgets.QLabel(self.widget)
        self.dl_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dl_label.setObjectName("dl_label")
        self.gridLayout.addWidget(self.dl_label, 3, 0, 1, 1)
        self.dl_comboBox = QtWidgets.QComboBox(self.widget)
        self.dl_comboBox.setMouseTracking(False)
        self.dl_comboBox.setObjectName("dl_comboBox")
        self.dl_comboBox.addItem("")
        self.dl_comboBox.addItem("")
        self.dl_comboBox.addItem("")
        self.dl_comboBox.addItem("")
        self.dl_comboBox.addItem("")
        self.dl_comboBox.addItem("")
        self.dl_comboBox.addItem("")
        self.dl_comboBox.addItem("")
        self.dl_comboBox.addItem("")
        self.dl_comboBox.addItem("")
        self.dl_comboBox.addItem("")
        self.gridLayout.addWidget(self.dl_comboBox, 3, 1, 1, 1)
        self.ds_labels = QtWidgets.QLabel(self.widget)
        self.ds_labels.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ds_labels.setObjectName("ds_labels")
        self.gridLayout.addWidget(self.ds_labels, 4, 0, 1, 1)
        self.ds_comboBox = QtWidgets.QComboBox(self.widget)
        self.ds_comboBox.setObjectName("ds_comboBox")
        self.ds_comboBox.addItem("")
        self.ds_comboBox.addItem("")
        self.ds_comboBox.addItem("")
        self.ds_comboBox.addItem("")
        self.ds_comboBox.addItem("")
        self.ds_comboBox.addItem("")
        self.ds_comboBox.addItem("")
        self.ds_comboBox.addItem("")
        self.ds_comboBox.addItem("")
        self.ds_comboBox.addItem("")
        self.ds_comboBox.addItem("")
        self.gridLayout.addWidget(self.ds_comboBox, 4, 1, 1, 1)
        self.verticalLayout.addWidget(self.foundation_groupBox)
        spacerItem = QtWidgets.QSpacerItem(20, 88, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.run_Button = QtWidgets.QPushButton(self.layoutWidget)
        self.run_Button.setMinimumSize(QtCore.QSize(0, 81))
        self.run_Button.setObjectName("run_Button")
        self.verticalLayout.addWidget(self.run_Button)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 731, 30))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Print = QtWidgets.QMenu(self.menu_File)
        self.menu_Print.setObjectName("menu_Print")
        self.menu_Import = QtWidgets.QMenu(self.menu_File)
        self.menu_Import.setObjectName("menu_Import")
        self.menu_Export = QtWidgets.QMenu(self.menu_File)
        self.menu_Export.setObjectName("menu_Export")
        self.menu_Help = QtWidgets.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Pdf = QtWidgets.QAction(MainWindow)
        self.action_Pdf.setEnabled(False)
        self.action_Pdf.setObjectName("action_Pdf")
        self.action_word = QtWidgets.QAction(MainWindow)
        self.action_word.setEnabled(False)
        self.action_word.setObjectName("action_word")
        self.action_About = QtWidgets.QAction(MainWindow)
        self.action_About.setObjectName("action_About")
        self.action_Autocad = QtWidgets.QAction(MainWindow)
        self.action_Autocad.setEnabled(False)
        self.action_Autocad.setObjectName("action_Autocad")
        self.action_Exit = QtWidgets.QAction(MainWindow)
        self.action_Exit.setObjectName("action_Exit")
        self.action_Safe = QtWidgets.QAction(MainWindow)
        self.action_Safe.setEnabled(False)
        self.action_Safe.setObjectName("action_Safe")
        self.menu_Print.addAction(self.action_Pdf)
        self.menu_Print.addAction(self.action_word)
        self.menu_Import.addAction(self.action_Safe)
        self.menu_Export.addAction(self.action_Autocad)
        self.menu_File.addAction(self.menu_Import.menuAction())
        self.menu_File.addAction(self.menu_Export.menuAction())
        self.menu_File.addAction(self.menu_Print.menuAction())
        self.menu_File.addAction(self.action_Exit)
        self.menu_Help.addAction(self.action_About)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        self.pos_comboBox.setCurrentIndex(0)
        self.dl_comboBox.setCurrentIndex(3)
        self.ds_comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.column_groupBox.setTitle(_translate("MainWindow", "Column"))
        self.h_label.setText(_translate("MainWindow", "C1"))
        self.c1_spinBox.setToolTip(_translate("MainWindow", "Height of foundation"))
        self.c1_spinBox.setSuffix(_translate("MainWindow", "  mm"))
        self.c2_label.setText(_translate("MainWindow", "C2"))
        self.c2_spinBox.setToolTip(_translate("MainWindow", "Height of foundation"))
        self.c2_spinBox.setSuffix(_translate("MainWindow", "  mm"))
        self.pos_label.setText(_translate("MainWindow", "pos"))
        self.pos_comboBox.setToolTip(_translate("MainWindow", "foundation  main rebars diameter"))
        self.pos_comboBox.setItemText(0, _translate("MainWindow", "center"))
        self.pos_comboBox.setItemText(1, _translate("MainWindow", "edge"))
        self.pos_comboBox.setItemText(2, _translate("MainWindow", "corner"))
        self.foundation_groupBox.setTitle(_translate("MainWindow", "Foundation"))
        self.height_label.setText(_translate("MainWindow", "Height"))
        self.height_spinBox.setSuffix(_translate("MainWindow", "  mm"))
        self.cover_label.setText(_translate("MainWindow", "cover"))
        self.cover_spinBox.setSuffix(_translate("MainWindow", "  mm"))
        self.fc_label.setText(_translate("MainWindow", "fc"))
        self.fc_spinBox.setSuffix(_translate("MainWindow", "  MPa"))
        self.dl_label.setText(_translate("MainWindow", "dl"))
        self.dl_comboBox.setToolTip(_translate("MainWindow", "foundation  main rebars diameter"))
        self.dl_comboBox.setItemText(0, _translate("MainWindow", "10"))
        self.dl_comboBox.setItemText(1, _translate("MainWindow", "12"))
        self.dl_comboBox.setItemText(2, _translate("MainWindow", "14"))
        self.dl_comboBox.setItemText(3, _translate("MainWindow", "16"))
        self.dl_comboBox.setItemText(4, _translate("MainWindow", "18"))
        self.dl_comboBox.setItemText(5, _translate("MainWindow", "20"))
        self.dl_comboBox.setItemText(6, _translate("MainWindow", "22"))
        self.dl_comboBox.setItemText(7, _translate("MainWindow", "25"))
        self.dl_comboBox.setItemText(8, _translate("MainWindow", "28"))
        self.dl_comboBox.setItemText(9, _translate("MainWindow", "30"))
        self.dl_comboBox.setItemText(10, _translate("MainWindow", "32"))
        self.ds_labels.setText(_translate("MainWindow", "ds"))
        self.ds_comboBox.setToolTip(_translate("MainWindow", "foundation shear rebars diameter"))
        self.ds_comboBox.setItemText(0, _translate("MainWindow", "10"))
        self.ds_comboBox.setItemText(1, _translate("MainWindow", "12"))
        self.ds_comboBox.setItemText(2, _translate("MainWindow", "14"))
        self.ds_comboBox.setItemText(3, _translate("MainWindow", "16"))
        self.ds_comboBox.setItemText(4, _translate("MainWindow", "18"))
        self.ds_comboBox.setItemText(5, _translate("MainWindow", "20"))
        self.ds_comboBox.setItemText(6, _translate("MainWindow", "22"))
        self.ds_comboBox.setItemText(7, _translate("MainWindow", "25"))
        self.ds_comboBox.setItemText(8, _translate("MainWindow", "28"))
        self.ds_comboBox.setItemText(9, _translate("MainWindow", "30"))
        self.ds_comboBox.setItemText(10, _translate("MainWindow", "32"))
        self.run_Button.setText(_translate("MainWindow", "&Run"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_Print.setTitle(_translate("MainWindow", "&Print"))
        self.menu_Import.setTitle(_translate("MainWindow", "&Import"))
        self.menu_Export.setTitle(_translate("MainWindow", "&Export"))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help"))
        self.action_Pdf.setText(_translate("MainWindow", "&pdf"))
        self.action_word.setText(_translate("MainWindow", "&word"))
        self.action_About.setText(_translate("MainWindow", "&About"))
        self.action_Autocad.setText(_translate("MainWindow", "&Autocad"))
        self.action_Exit.setText(_translate("MainWindow", "E&xit"))
        self.action_Exit.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.action_Safe.setText(_translate("MainWindow", "&Safe"))

